<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <!-- Define materials -->
    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- Define parameters -->
    <xacro:property name="body_length" value="0.485"/>
    <xacro:property name="body_width" value="0.31"/>
    <xacro:property name="body_height" value="0.345"/>
    <xacro:property name="wheel_radius" value="0.055" />
    <xacro:property name="wheel_length" value="0.06" />
    <xacro:property name="material_density" value="1180" />
    <xacro:property name="body_mass" value="8" />
    <xacro:property name="wheel_mass" value="1" />

    <!-- BASE LINK -->

    <link name="base_link">
    
    </link>

    <!--BODY LINK -->

    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="body">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${body_mass}" x="0.485" y="0.31" z="0.345">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="body">
            <material>Gazebo/White</material>
            <mul1>0.01</mul1>
            <mul2>0.01</mul2>
        </gazebo>

    <!-- LEFT FRONT WHEEL LINK-->

    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="${body_length/2-1.2*wheel_radius} ${-body_width/2-wheel_length/2} ${-body_height/2}" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_front_wheel">
            <material>Gazebo/Black</material>
            <mul1>0.01</mul1>
            <mul2>0.01</mul2>
        </gazebo>

    <!-- RIGHT FRONT WHEEL LINK-->

    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="${body_length/2-1.2*wheel_radius} ${body_width/2+wheel_length/2} ${-body_height/2}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_front_wheel">
        <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_front_wheel">
            <material>Gazebo/Black</material>
            <mul1>0.01</mul1>
            <mul2>0.01</mul2>
        </gazebo>


    <!-- LEFT REAR WHEEL LINK-->

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_rear_wheel"/>
        <origin xyz="${-body_length/2+1.2*wheel_radius} ${-body_width/2-wheel_length/2} ${-body_height/2}" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_rear_wheel">
        <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_rear_wheel">
            <material>Gazebo/Black</material>
            <mul1>0.01</mul1>
            <mul2>0.01</mul2>
        </gazebo>

    <!-- RIGHT REAR WHEEL LINK-->

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_rear_wheel"/>
        <origin xyz="${-body_length/2+1.2*wheel_radius} ${body_width/2+wheel_length/2} ${-body_height/2}" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_rear_wheel">
        <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_rear_wheel">
            <material>Gazebo/Black</material>
            <mul1>0.01</mul1>
            <mul2>0.01</mul2>
        </gazebo>

</robot>